version: "3"
services:
    # imagem
    aovivo:
        build:
            context: ./
            dockerfile: Dockerfile
        image: laravel-app
        restart: unless-stopped
        working_dir: /var/www/
        volumes:
            - ./:/var/www
        networks:
            - aovivo

    # nginx
    nginx:
        image: nginx:alpine
        restart: unless-stopped
        ports:
            - 8081:80
        volumes:
            - ./:/var/www
            - ./docker/nginx/:/etc/nginx/conf.d/
        networks:
            - aovivo

networks:
    aovivo:
        driver: bridge
