version: "3"
services:
    # imagem
    laravelApp:
        container_name: app_laravel
        build:
            context: ./
            dockerfile: Dockerfile
        image: laravel-app
        restart: unless-stopped
        working_dir: /var/www/
        volumes:
            - ./:/var/www
        networks:
            - laravelNet

    # nginx
    nginx:
        container_name: web_laravel
        image: nginx:alpine
        restart: unless-stopped
        ports:
            - 8008:80
        volumes:
            - ./:/var/www
            - ./docker/nginx/:/etc/nginx/conf.d/
        networks:
            - laravelNet

networks:
    laravelNet:
        driver: bridge
